Construction_Management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('mainfunction/', include('mainfunction.urls'))
]

login/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 14 12:04:19 2019

@author: harid
"""
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
            path('', views.login, name='login'),
            path('signup/', views.signup, name='signup'),
            path('register/', views.register, name='register'),
            path('authenticate/', views.authenticate, name='authenticate'),
            path('confirmation/', views.confirmation, name='confirmation')
        ]

mainfunction/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 14 17:36:57 2019

@author: harid
"""
from django.urls import path
from . import views

app_name = 'mainfunction'

urlpatterns = [
            path('', views.dashboard, name='dashboard'),
            path('additem/', views.add_item, name='add_item'),
            path('dailydetails/<project_name>/', views.add_daily_details,
                 name='add_daily_details')
        ]

login/models.py
from django.db import models

# Create your models here.
class UserDetails(models.Model):
    user_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200, primary_key=True)
    password = models.CharField(max_length=200)

login/views.py
from django.shortcuts import render
import sys
import random
from .models import UserDetails
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from login.passwordvalidation import PasswordValidation
from django.db import connection
from django.core.mail import BadHeaderError, send_mail
# Create your views here.
counter = 0

def signup(request):
    error = request.GET.get('error')
    
    if(error == 'email_exists'):
        context = {'error':"Email ID already exists!"}
        return render(request, "login/signup_form.html", context)
    
    elif(error == 'invalid_password'):
        context = {'error':"Invalid Password!\nPassword should contain"\
                   " atleast one small letter, capital letter, number and a"\
                   " special character.The length should be atleast "\
                   "8 characters."}
        return render(request, "login/signup_form.html", context)
    
    else:
        return render(request, "login/signup_form.html")

def login(request):
    error = request.GET.get('error')
    if(error == 'wrong'):
        context = {'error':"Wrong Username or Password!"}
        
        return render(request, "login/login_form.html", context)
    else:
        
        return render(request, "login/login_form.html")
    
def register(request):
    user_name = request.POST['inputUname']
    u_email = request.POST['inputEmail']
    u_password = request.POST['inputPassword']
    try:
        u_name = UserDetails.objects.get(email=u_email)
    except:
        Validate_Password = PasswordValidation()
        validity_check = Validate_Password.validity(u_password)
        
        if(validity_check == "Valid"):
            ud_object = UserDetails(user_name=user_name, email=u_email,
                            password=u_password)
            ud_object.save()
            try:
                code = random.randint(1,1000000)
                print(code)
                subject = "Registration Code"
                message = "Your registration code is : " + str(code) +"\n\n\nWith"\
                " Regard,\nHaridutt Jani"
                from_email = "hariduttjani@gmail.com"
                to_mail = u_email
                send_mail(subject, message, from_email,
                          [to_mail])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            context = {'error':'', 'code':code, 'email':u_email, 'counter':0}
            return render(request, 'login/confirmation.html', context)
        else:
            return HttpResponseRedirect(reverse("login:signup")
                                        + "?error=invalid_password")
            
    return HttpResponseRedirect(reverse("login:signup")
                                + "?error=email_exists")
        
def authenticate(request):
    u_email = request.POST['inputEmail']
    u_password = request.POST['inputPassword']

    cursor = connection.cursor()
    
    cursor.execute("SELECT user_name FROM `login_userdetails`"\
                                         "WHERE email='" + u_email
                                         + "' and BINARY password='"
                                         +u_password + "'")
    u_name_tupple = cursor.fetchone()
    
    if(u_name_tupple == None):
        return HttpResponseRedirect(reverse("login:login") + "?error=wrong")
    
    u_name = u_name_tupple[0]
    if(u_name != "" or u_name != None):
        return HttpResponseRedirect(reverse("mainfunction:dashboard") 
                                    + "?user=" + str(u_name))    
def confirmation(request):
    email = request.GET.get('email')
    code = request.POST["code"]
    confirmation_code = request.POST["inputCode"]
    
    print(int(code))
    print(int(confirmation_code))
    if(int(confirmation_code) == int(code)):
        return HttpResponseRedirect(reverse("login:login")
                                    + "?Registration Successfully!")
    else:
        count = request.POST["counter"]
        
        if(int(count) >= 3):
            UserDetails.objects.filter(email=email).delete()
            return HttpResponseRedirect(reverse("login:signup"))
        else:
            counter = int(count) + 1
            if(int(count) == 2):
                error = "This is your last chance, else you will be redirected to signup page again."
            else:
                error = 'Incorrect Code!'
            context = {'error':error, 'code':code,
                       'email':email, 'counter':counter}
            return render(request, 'login/confirmation.html', context)

login/templates/login/confirmation.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta http-equiv="content-type" content="text/html; charset=UTF-8">

  <title>Login - Construction Management</title>

  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,400italic,700,900' rel='stylesheet' type='text/css'>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Techie Bootstrap 3 skin">
  <meta name="keywords" content="bootstrap 3, skin, flat">
  <meta name="author" content="bootstraptaste">

  <!-- Bootstrap css -->
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.min.css' %}" rel="stylesheet">
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.techie.css' %}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Techie
    Theme URL: https://bootstrapmade.com/techie-free-skin-bootstrap-3/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->

  <!-- Docs Custom styles -->
  <style>
    body,
    html {
      overflow-x: hidden
    }

    body {
      padding: 60px 20px 0
    }

    footer {
      border-top: 1px solid #ddd;
      padding: 30px;
      margin-top: 50px
    }

    .row>[class*=col-] {
      margin-bottom: 40px
    }

    .navbar-container {
      position: relative;
      min-height: 100px
    }

    .navbar.navbar-fixed-bottom,
    .navbar.navbar-fixed-top {
      position: absolute;
      top: 50px;
      z-index: 0
    }

    .navbar.navbar-fixed-bottom .container,
    .navbar.navbar-fixed-top .container {
      max-width: 90%
    }

    .btn-group {
      margin-bottom: 10px
    }

    .form-inline input[type=password],
    .form-inline input[type=text],
    .form-inline select {
      width: 180px
    }

    .input-group {
      margin-bottom: 10px
    }

    .pagination {
      margin-top: 0
    }
  </style>

</head>

<body>
  <div class="container-fluid text-center" style="background-color: #414141; margin-bottom: 20px">
    <h2 style="color: #ffffff">Construction Management</h2>
  </div>

  <div class="row">
    <div class="col-sm-12 col-lg-12">
      <div class="row">
        <div class="container">
          {% if error %}
            <div style="color: red"> {{ error }} </div>
          {% endif %}
          <form class="form-horizontal" action="{% url 'login:confirmation'%}?email={{ email }}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="inputCode" class="col-lg-2 control-label">Confirmation Code</label>
              <div class="col-lg-10">
                <input type="text" class="form-control" id="inputCode" name="inputCode" placeholder="Enter the code sent to your email">
              </div>
            </div>
            <input hidden type="text" name="code" value="{{ code }}">
            <input hidden type="text" name="counter" value="{{ counter }}">
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <button type="submit" class="btn btn-default">CONFIRM</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <footer class="text-center">
    <p>&copy; Construction Management</p>
    <div class="credits">
      <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version form: https://bootstrapmade.com/buy/?theme=Techie
      -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer>

  <!-- Main Scripts-->
  {% load static %}
  <script src="{% static 'login/jquery.js' %}"></script>
  {% load static %}
  <script src="{% static 'login/bootstrap.min.js' %}"></script>

  <!-- Bootstrap 3 has typeahead optionally -->
  {% load static %}
  <script src="{% static 'login/typeahead.min.js' %}"></script>   
</body>
</html>

login/templates/login/login_form.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta http-equiv="content-type" content="text/html; charset=UTF-8">

  <title>Login - Construction Management</title>

  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,400italic,700,900' rel='stylesheet' type='text/css'>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Techie Bootstrap 3 skin">
  <meta name="keywords" content="bootstrap 3, skin, flat">
  <meta name="author" content="bootstraptaste">

  <!-- Bootstrap css -->
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.min.css' %}" rel="stylesheet">
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.techie.css' %}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Techie
    Theme URL: https://bootstrapmade.com/techie-free-skin-bootstrap-3/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->

  <!-- Docs Custom styles -->
  <style>
    body,
    html {
      overflow-x: hidden
    }

    body {
      padding: 60px 20px 0
    }

    footer {
      border-top: 1px solid #ddd;
      padding: 30px;
      margin-top: 50px
    }

    .row>[class*=col-] {
      margin-bottom: 40px
    }

    .navbar-container {
      position: relative;
      min-height: 100px
    }

    .navbar.navbar-fixed-bottom,
    .navbar.navbar-fixed-top {
      position: absolute;
      top: 50px;
      z-index: 0
    }

    .navbar.navbar-fixed-bottom .container,
    .navbar.navbar-fixed-top .container {
      max-width: 90%
    }

    .btn-group {
      margin-bottom: 10px
    }

    .form-inline input[type=password],
    .form-inline input[type=text],
    .form-inline select {
      width: 180px
    }

    .input-group {
      margin-bottom: 10px
    }

    .pagination {
      margin-top: 0
    }
  </style>

</head>

<body>
  <div class="container-fluid text-center" style="background-color: #414141; margin-bottom: 20px">
    <h2 style="color: #ffffff">Construction Management</h2>
  </div>

  <div class="row">
    <div class="col-sm-12 col-lg-12">
      <div class="row">
        <div class="container">
          {% if error %}
            <div style="color: red"> {{ error }} </div>
          {% endif %}
          <form class="form-horizontal" action="{% url 'login:authenticate' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="inputEmail" class="col-lg-2 control-label">Email</label>
              <div class="col-lg-10">
                <input type="text" class="form-control" id="inputEmail" name="inputEmail" placeholder="Email">
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword" class="col-lg-2 control-label">Password</label>
              <div class="col-lg-10">
                <input type="password" class="form-control" id="inputPassword" name="inputPassword" placeholder="Password">
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <!--<div class="checkbox">
                  <label>
                    <input type="checkbox"> Remember me
                  </label>
                </div>-->
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <button type="submit" class="btn btn-default">Login</button>
              </div>
            </div>
          </form>
          <a href="{% url 'login:signup' %}">Don't have an account? Sign Up here.</a>
        </div>
      </div>
    </div>
  </div>
  <footer class="text-center">
    <p>&copy; Construction Management</p>
    <div class="credits">
      <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version form: https://bootstrapmade.com/buy/?theme=Techie
      -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer>

  <!-- Main Scripts-->
  {% load static %}
  <script src="{% static 'login/jquery.js' %}"></script>
  {% load static %}
  <script src="{% static 'login/bootstrap.min.js' %}"></script>

  <!-- Bootstrap 3 has typeahead optionally -->
  {% load static %}
  <script src="{% static 'login/typeahead.min.js' %}"></script>   
</body>
</html>

login/templates/login/signup_form.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta http-equiv="content-type" content="text/html; charset=UTF-8">

  <title>Signup - Construction Management</title>

  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,400italic,700,900' rel='stylesheet' type='text/css'>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Techie Bootstrap 3 skin">
  <meta name="keywords" content="bootstrap 3, skin, flat">
  <meta name="author" content="bootstraptaste">

  <!-- Bootstrap css -->
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.min.css' %}" rel="stylesheet">
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.techie.css' %}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Techie
    Theme URL: https://bootstrapmade.com/techie-free-skin-bootstrap-3/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->

  <!-- Docs Custom styles -->
  <style>
    body,
    html {
      overflow-x: hidden
    }

    body {
      padding: 60px 20px 0
    }

    footer {
      border-top: 1px solid #ddd;
      padding: 30px;
      margin-top: 50px
    }

    .row>[class*=col-] {
      margin-bottom: 40px
    }

    .navbar-container {
      position: relative;
      min-height: 100px
    }

    .navbar.navbar-fixed-bottom,
    .navbar.navbar-fixed-top {
      position: absolute;
      top: 50px;
      z-index: 0
    }

    .navbar.navbar-fixed-bottom .container,
    .navbar.navbar-fixed-top .container {
      max-width: 90%
    }

    .btn-group {
      margin-bottom: 10px
    }

    .form-inline input[type=password],
    .form-inline input[type=text],
    .form-inline select {
      width: 180px
    }

    .input-group {
      margin-bottom: 10px
    }

    .pagination {
      margin-top: 0
    }
  </style>
  <script type="text/javascript">
    function emailValidation(email){
      var reg = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}         \])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
      return reg.test(email);
    }
    function validateEmail(){
      var $error = $('#error');
      var email = $('#inputEmail').val();
      if(!emailValidation(email)){
        $error.text("Email is not valid");
        var btn = document.getElementById("signup");
        btn.disabled = true;  
      }
      else{
        $error.text(""); 
        var btn = document.getElementById("signup");
        btn.disabled = false;
      }
      return false;
    }
  </script>
</head>

<body>
  <div class="container-fluid text-center" style="background-color: #414141; margin-bottom: 20px">
    <h2 style="color: #ffffff">Construction Management</h2>
  </div>

  <div class="row">
    <div class="col-sm-12 col-lg-12">
      <div class="row">
        <div class="container">
        <div id="error" style="color: red"></div>  
        {% if error %}<div style="color: red">{{error}}</div>{% endif %}           
          <form class="form-horizontal" action="{% url 'login:register' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="inputUname" class="col-lg-2 control-label">Username</label>
              <div class="col-lg-10">
                <input type="text" class="form-control" id="inputUname" name="inputUname" placeholder="Username">
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail" class="col-lg-2 control-label">Email</label>
              <div class="col-lg-10">
                <input type="text" class="form-control" id="inputEmail" name="inputEmail" placeholder="Email" onkeypress="validateEmail()">
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword" class="col-lg-2 control-label">Password</label>
              <div class="col-lg-10">
                <input type="password" class="form-control" id="inputPassword" name="inputPassword" placeholder="Password">
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-10">
                <button type="submit" id="signup" class="btn btn-default">Sign up</button>
              </div>
            </div>
          </form>
          <a href="{% url 'login:login' %}">Already have an account? Login here.</a>
        </div>
      </div>
    </div>
  </div>
  <footer class="text-center">
    <p>&copy; Construction Management</p>
    <div class="credits">
      <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version form: https://bootstrapmade.com/buy/?theme=Techie
      -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer>

  <!-- Main Scripts-->
  {% load static %}
  <script src="{% static 'login/jquery.js' %}"></script>
  {% load static %}
  <script src="{% static 'login/bootstrap.min.js' %}"></script>

  <!-- Bootstrap 3 has typeahead optionally -->
  {% load static %}
  <script src="{% static 'login/typeahead.min.js' %}"></script>   
</body>
</html>

login/templates/login/test.html
<html>
<head>
	<title>Check</title>
	<link href='https://fonts.googleapis.com/css?family=Lato:400,300,400italic,700,900' rel='stylesheet' type='text/css'>
  	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  	<meta name="description" content="Techie Bootstrap 3 skin">
  	<meta name="keywords" content="bootstrap 3, skin, flat">
  	<meta name="author" content="bootstraptaste">

  	<!-- Bootstrap css -->
  	{% load static %}
  	<link type="text/css" href="{% static 'login/bootstrap.min.css' %}" rel="stylesheet">
  	{% load static %}
	<link type="text/css" href="{% static 'login/bootstrap.techie.css' %}" rel="stylesheet">
</head>
<body>
	<div class="container-fluid text-center" style="background-color: #414141; margin-bottom: 20px">
    	<h2 style="color: #ffffff">Construction Management</h2>
    	<a href="{% url 'mainfunction:dashboard' %}?user={{ user }}" class="btn btn-primary" style="float: left; color: #ffffff;">Back</a>
    	<a href="{% url 'login:login' %}" class="btn btn-primary" style="float: right; color: #ffffff;">Logout</a>
  	</div>

  	<div class="row">
    	<div class="col-sm-12 col-lg-12">
      		<div class="row">
        		<div class="container">
          			{% if error %}
            		<div style="color: red"> {{ error }} </div>
          			{% endif %}
					<form class="form-horizontal" action="{% url 'login:test' %}" method="post">
						{% csrf_token %}
						{% for field in form %}
							<div class="form-group">
						      <label for="{{ field.id_for_lable }}" class="col-lg-2 control-label">{{ field.html_name }}</label>
						      <div class="col-lg-10">
						        {{ field }}
						      </div>
						    </div>
						{% endfor %}    
						<div class="form-group">
					      <div class="col-lg-offset-2 col-lg-10">
					        <button type="submit" class="btn btn-default">Login</button>
					      </div>
					    </div>
					</form>
				</div>
			</div>
    	</div>
  </div>
  <footer class="text-center">
    <p>&copy; Construction Management</p>
    <div class="credits">
      <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version form: https://bootstrapmade.com/buy/?theme=Techie
      -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer>

  <!-- Main Scripts-->
  {% load static %}
  <script src="{% static 'login/jquery.js' %}"></script>
  {% load static %}
  <script src="{% static 'login/bootstrap.min.js' %}"></script>

  <!-- Bootstrap 3 has typeahead optionally -->
  {% load static %}
  <script src="{% static 'login/typeahead.min.js' %}"></script>	
</body>
<html>