Construction_Management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('mainfunction/', include('mainfunction.urls'))
]

login/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 14 12:04:19 2019

@author: harid
"""
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
            path('', views.login, name='login'),
            path('signup/', views.signup, name='signup'),
            path('register/', views.register, name='register'),
            path('authenticate/', views.authenticate, name='authenticate'),
            path('confirmation/', views.confirmation, name='confirmation')
        ]

mainfunction/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 14 17:36:57 2019

@author: harid
"""
from django.urls import path
from . import views

app_name = 'mainfunction'

urlpatterns = [
            path('', views.dashboard, name='dashboard'),
            path('additem/', views.add_item, name='add_item'),
            path('dailydetails/<project_name>/', views.add_daily_details,
                 name='add_daily_details')
        ]

mainfunction/models.py
from django.db import models
from login.models import UserDetails
# Create your models here.
class ProjectDetails(models.Model):
    constructer_details = models.ForeignKey(UserDetails,
                                            on_delete=models.CASCADE)
    project_name = models.CharField(max_length=200)
    client_name = models.CharField(max_length=200)
    starting_date = models.DateField()
    ending_date = models.DateField()
    location = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    
class DailyDetails(models.Model):
    project_details = models.ForeignKey(ProjectDetails, on_delete=models.CASCADE)
    day = models.IntegerField(primary_key=True)
    task_status = models.CharField(max_length=5)
    reason = models.CharField(max_length=200)

mainfunction/forms.py
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 18 17:54:59 2019

@author: harid
"""
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class AddProjectDetails(forms.Form):
    inputProjectName = forms.CharField(
                    label = "Project Name",
                    required=True,
                    widget = forms.TextInput(attrs={'class':'form-control',
                                                    'id':"inputProjectName",
                                                    'name':"inputProjectName",
                                                    'placeholder':"Name of the project"}),
                    max_length=200
                    )
    inputClientName = forms.CharField(
                    label = "Client Name",
                    required=True,
                    widget = forms.TextInput(attrs={'class':'form-control',
                                                    'id':"inputClientName",
                                                    'name':"inputClientName",
                                                    'placeholder':"Name of the client"}),
                    max_length=200
                    )
    inputStartingDate = forms.DateField(
                    label = "Starting Date",
                    required=True,
                    widget = forms.DateInput(attrs={'class':'form-control',
                                                    'type':'Date',
                                                    'id':'inputStartingDate',
                                                    'name':'inputStartingDate',
                                                    'onchange':"date_check('inputStartingDate')"})
                    )
    inputEndingDate = forms.DateField(
                    label = "Ending Date",
                    required=True,
                    widget = forms.DateInput(attrs={'class':'form-control',
                                                    'type':'Date',
                                                    'id':'inputEndingDate',
                                                    'name':'inputEndingDate',
                                                    'onchange':"date_cmp('inputEndingDate')"})
                    )
    inputLocation = forms.CharField(
                    label = "Location",
                    required=True,
                    widget = forms.TextInput(attrs={'class':'form-control',
                                                    'id':'inputLocation',
                                                    'name':'inputLocation',
                                                    'placeholder':"Entre the location of the construction"}),
                    max_length=200
                    )
    inputCity = forms.CharField(
                    label = "City",
                    required=True,
                    widget = forms.TextInput(attrs={'class':'form-control',
                                                    'id':'inputCity',
                                                    'name':'inputCity',
                                                    'placeholder':"City"}),
                    max_length=200
                    )
    
    def clean_date(self):
        date_starting = self.cleaned_data['inputStartingDate']
        date_ending = self.cleaned_data['inputEndingDate']
        
        # Check if a date is not in the past. 
        if(date_starting < datetime.date.today() or date_ending < datetime.date.today()):
            raise ValidationError(_('Starting/Ending date must not be in past.'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if(date_starting > date_ending):
            raise ValidationError(_('Starting date must be less than ending date.'))

        # Remember to always return the cleaned data.
        return date_starting, date_ending
    

mainfunction/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone
import datetime
import json
from .forms import AddProjectDetails
from django.db import connection
from .models import ProjectDetails, DailyDetails
from login.models import UserDetails
from .weatherverification import WeatherValidation
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
# Create your views here.
def dashboard(request):
    user_name = request.GET.get('user')
    user_details = UserDetails.objects.get(user_name=user_name)
    
    if(request.method == 'POST'):
        project_name = request.POST["inputProjectName"]
        client_name = request.POST["inputClientName"]
        starting_date = request.POST["inputStartingDate"]
        ending_date = request.POST["inputEndingDate"]
        location = request.POST["inputLocation"]
        city = request.POST["inputCity"]
        
        project_details_record = ProjectDetails(project_name = project_name,
                                                client_name = client_name,
                                                starting_date = starting_date,
                                                ending_date = ending_date,
                                                location = location,
                                                city = city,
                                                constructer_details 
                                                    = user_details)
        project_details_record.save()
        
    project_name_list = ProjectDetails.objects.filter(constructer_details
                                                      =user_details).values_list('project_name')
    project_location_list = ProjectDetails.objects.filter(constructer_details
                                                          =user_details).values_list('location')
    project_startdate_list = ProjectDetails.objects.filter(constructer_details
                                                           =user_details).values_list('starting_date')
    project_enddate_list = ProjectDetails.objects.filter(constructer_details
                                                           =user_details).values_list('ending_date')
    
    project_name = []
    project_location = []
    project_startdate = []
    project_enddate = []
    for i in range(len(project_name_list)):
        project_name.append(project_name_list[i][0])
        project_location.append(project_location_list[i][0])
        project_startdate.append(project_startdate_list[i][0])
        project_enddate.append(project_enddate_list[i][0])
    
    project_status = []
    project_days = []
    now = datetime.date.today()
    for date_start, date_end in zip(project_startdate, project_enddate):
        delta = now - date_start
        if(date_start > now):
            project_status.append("Upcoming")
        elif(date_start <= now and date_end >= now):
            project_status.append("Ongoing")
        elif(now > date_end):
            project_status.append("Completed")
        project_days.append(delta.days + 1)

    print(project_name)
    print(project_location)
    print(project_startdate)
    print(project_enddate)
    print(project_status)
    print(project_days)
        
    project_details_list = list(zip(project_name, project_location,
                                    project_days, project_status))
    print(project_details_list)
    context = {'user':user_name, 'project_details':project_details_list}
    
    return render(request, "mainfunction/dashboard.html", context)
        
def add_item(request):
    if(request.method == 'POST'):
        print("1")
        form = AddProjectDetails()
        print("2")
        form = AddProjectDetails(request.POST)
        if(form.is_valid()):
            try:
                form.clean_date()
            except ValidationError as error:
                print(repr(error.message))
                Response = HttpResponse(
                            json.dumps({'Error':repr(error.message)}),
                            content_type = "application/json"
                            )
                return Response
            Response = HttpResponse(
                            json.dumps({'Error':""}),
                            content_type = "application/json"
                            )
            return Response
        Response = HttpResponse(
                            json.dumps({'Error':"Some field(s) contains invalid data."}),
                            content_type = "application/json"
                            )
        return Response
    user_name = request.GET.get('user')
    form = AddProjectDetails()
    context = {'user':user_name, 'form':form}
    return render(request, "mainfunction/add_project_form.html", context)

def add_daily_details(request, project_name):
    user_name = request.GET.get("user")
    user_details = UserDetails.objects.get(user_name=user_name)
    project = ProjectDetails.objects.get(constructer_details=user_details,
                                         project_name=project_name)
    date = project.starting_date
    end_date = project.ending_date
    city = project.city
    now = datetime.date.today()
    delta = now - date
    message = ""
    if(now < date):
        message = "Project has not been started yet!"
    elif(end_date < now):
        message = "Project has been finished!"
    days = delta.days + 1
    invalid_reason = ""
    
    if(request.method == 'POST'):
        task_status = request.POST["inputTaskStatus"]
        reason = request.POST["inputReason"]
        if(task_status == "Not Completed"):
            weather_check = WeatherValidation()
            weather_info = weather_check.getWeather_from_City(city)
            print("weather_info")
            print(weather_info)
            check = weather_check.validate_reason(reason, weather_info)
            if(check):
                daily_details_record = DailyDetails(project_details=project,
                                                    day=days,
                                                    task_status=task_status,
                                                    reason=reason)
                daily_details_record.save()
            else:
                invalid_reason = "Reason of bad weather is invalid!"
                daily_details_record = DailyDetails(project_details=project,
                                                    day=days,
                                                    task_status=task_status,
                                                    reason="No valid reason.")
                daily_details_record.save()
        else:
            daily_details_record = DailyDetails(project_details=project,
                                                day=days,
                                                task_status=task_status,
                                                reason="All Good")
            daily_details_record.save()
        
    daily_days_list = DailyDetails.objects.filter(project_details=project).values_list('day')
    daily_taskstatus_list = DailyDetails.objects.filter(project_details=project).values_list('task_status')
    daily_reason_list = DailyDetails.objects.filter(project_details=project).values_list('reason')
    
    daily_days = []
    daily_taskstatus = []
    daily_reason = []
    
    for i in range(len(daily_days_list)):
        daily_days.append(daily_days_list[i][0])
        daily_taskstatus.append(daily_taskstatus_list[i][0])
        daily_reason.append(daily_reason_list[i][0])
    
    daily_details_list = list(zip(daily_days, daily_taskstatus, daily_reason))

    context = {'user':user_name, 'days':days,'project_name':project_name,
               'daily_details':daily_details_list,
               'invalid_reason':invalid_reason,
               'message':message}

    return render(request, "mainfunction/add_daily_details.html", context)

mainfunction/templates/mainfunction/add_daily_details.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta http-equiv="content-type" content="text/html; charset=UTF-8">

  <title>Login - Construction Management</title>

  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,400italic,700,900' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Techie Bootstrap 3 skin">
  <meta name="keywords" content="bootstrap 3, skin, flat">
  <meta name="author" content="bootstraptaste">

  <!-- Bootstrap css -->
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.min.css' %}" rel="stylesheet">
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.techie.css' %}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Techie
    Theme URL: https://bootstrapmade.com/techie-free-skin-bootstrap-3/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->

  <!-- Docs Custom styles -->
  <style>
    body,
    html {
      overflow-x: hidden
    }

    body {
      padding: 60px 20px 0
    }

    footer {
      border-top: 1px solid #ddd;
      padding: 30px;
      margin-top: 50px
    }

    table, th, td{
      border : 1px solid black;
      border-collapse : collapse;
    }
  
    th, td{
      text-align : center;
      padding : 5px;
    }

    .row>[class*=col-] {
      margin-bottom: 40px
    }

    .navbar-container {
      position: relative;
      min-height: 100px
    }

    .navbar.navbar-fixed-bottom,
    .navbar.navbar-fixed-top {
      position: absolute;
      top: 50px;
      z-index: 0
    }

    .navbar.navbar-fixed-bottom .container,
    .navbar.navbar-fixed-top .container {
      max-width: 90%
    }

    .btn-group {
      margin-bottom: 10px
    }

    .form-inline input[type=password],
    .form-inline input[type=text],
    .form-inline select {
      width: 180px
    }

    .input-group {
      margin-bottom: 10px
    }

    .pagination {
      margin-top: 0
    }
  </style>
  <script type="text/javascript">
      console.log("In script");
      function hideForm(){
        document.getElementById("form").style.visibility = "hidden";
      }
  </script>
</head>

<body>
  <div class="container-fluid text-center" style="background-color: #414141; margin-bottom: 20px">
    <h2 style="color: #ffffff">Construction Management</h2>
    <a href="{% url 'mainfunction:dashboard' %}?user={{ user }}" class="btn btn-primary" style="float: left; color: #ffffff;">Back</a>
    <a href="{% url 'login:login' %}" class="btn btn-primary" style="float: right; color: #ffffff;">Logout</a>
  </div>

  <p style="text-align: center; border-bottom: 2px solid #414141"><strong>Add today's details</strong></p>
  <div style="margin-left: auto; margin-right: auto; display: block;">
    <form id="form" class="form-horizontal" action="{% url 'mainfunction:add_daily_details' project_name=project_name %}?user={{ user }}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label class="col-lg-2 control-label">Task Completed</label>
        <div class="col-lg-10">
          <input type="radio" id="inputTaskStatusYes" name="inputTaskStatus" value="Completed">Yes
          <br>
          <input type="radio" id="inputTaskStatusNo" name="inputTaskStatus" value="Not Completed">No
        </div>
      </div>
      <div class="form-group">
        <label for="inputReason" class="col-lg-2 control-label">Reason</label>
        <div class="col-lg-10">
          <input list="reason" name="inputReason">
          <datalist id="reason">
            <option value="All Good">
            <option value="High Wind/Cyclone">
            <option value="Storm">
            <option value="Heavy Rain">
            <option value="Ice Fall">
            <option value="Heat wave/Strong sun">
          </datalist>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
          <button type="submit" class="btn btn-default">ADD</button>
        </div>
      </div>
      <div style="color: red">{{ invalid_reason }}</div>
    </form>
  </div>
  {% if message %}
  <div>
    {{ message }}
    <script type="text/javascript">
      console.log("In here")
      hideForm()
    </script>
  </div>
  {% endif %}        
  <br><br>

  <p style="margin-top: 4px; text-align: center; border-top: 1px solid #414141; border-bottom: 2px solid #414141"><strong>Daily details</strong></p>
  <br>
  <div class="container">
    <table class="table table-striped table-hover" id="myTable">
      <thead>
        <tr style="text-align: center;">
          <th>Day</th>
          <th>Task Status</th>
          <th>Reason</th>
        </tr>
      </thead>
      <tbody id="viewer">
        {% for details in daily_details %}
          <tr>
            <td> {{ details.0 }} </td>
            <td> {{ details.1 }} </td>
            <td> {{ details.2 }} </td>
          </tr>
        {% endfor %}
      </tbody>    
    </table>
  </div>
</body>
</html>  

mainfunction/templates/mainfunction/add_project_form.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta http-equiv="content-type" content="text/html; charset=UTF-8">

  <title>Login - Construction Management</title>


  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,400italic,700,900' rel='stylesheet' type='text/css'>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Techie Bootstrap 3 skin">
  <meta name="keywords" content="bootstrap 3, skin, flat">
  <meta name="author" content="bootstraptaste">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.min.css' %}" rel="stylesheet">
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.techie.css' %}" rel="stylesheet">
  <script type="text/javascript">
  	function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
	}

	function csrfSafeMethod(method) {
    	// these HTTP methods do not require CSRF protection
    	return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	}

  	function loadDoc(){
		$(document).ready(function(){
			var csrftoken = getCookie('csrftoken');
			$.ajaxSetup({
			    beforeSend: function(xhr, settings) {
			        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
			            xhr.setRequestHeader("X-CSRFToken", csrftoken);
			        }
			    }
			});
			$.post("{% url 'mainfunction:add_item' %}", 
				{
					inputProjectName : document.getElementById('inputProjectName').value,
					inputClientName : document.getElementById('inputClientName').value, 
					inputStartingDate : document.getElementById('inputStartingDate').value,
					inputEndingDate : document.getElementById('inputEndingDate').value,
					inputLocation : document.getElementById('inputLocation').value,
					inputCity : document.getElementById('inputCity').value
				},
				function(json_responser){
					var response = json_responser.Error;
					$("#err").html(response);
					if(response == ""){
						$.post("{% url 'mainfunction:dashboard' %}?user={{ user }}", 
						{
							inputProjectName : document.getElementById('inputProjectName').value,
							inputClientName : document.getElementById('inputClientName').value, 
							inputStartingDate : document.getElementById('inputStartingDate').value,
							inputEndingDate : document.getElementById('inputEndingDate').value,
							inputLocation : document.getElementById('inputLocation').value,
							inputCity : document.getElementById('inputCity').value
						},
						function(data)
						{
							console.log(data.redirect);
							window.location.href = "{% url 'mainfunction:dashboard' %}?user={{ user }}";
						});
					}
				}
			);
		});
	}

  	function date_check(id_name){
  		var date = document.getElementById(id_name).value;
  		var entered_date = new Date(date);
  		var now = new Date();
  		if(entered_date < now){
  			var btn = document.getElementById("add");
  			btn.disabled = true;
  			alert("Enter the date which is not in past.");
  		}
  		else{
  			var btn = document.getElementById("add");
  			btn.disabled = false;	
  		}
  	}

  	function date_cmp(id_name){
  		date_check(id_name);
  		var start = document.getElementById("inputStartingDate").value;
  		var end = document.getElementById("inputEndingDate").value;
  		var start_date = new Date(start);
  		var end_date = new Date(end);
  		if(end_date <= start_date){
  			var btn = document.getElementById("add");
  			btn.disabled = true;
  			alert("Ending date have to be ahead of starting date.");	
  		}
  		else{
  			var btn = document.getElementById("add");
  			btn.disabled = false;
  		}
  	}
  </script>
  <style>
    body,
    html {
      overflow-x: hidden
    }

    body {
      padding: 60px 20px 0
    }

    footer {
      border-top: 1px solid #ddd;
      padding: 30px;
      margin-top: 50px
    }

    .row>[class*=col-] {
      margin-bottom: 40px
    }

    .navbar-container {
      position: relative;
      min-height: 100px
    }

    .navbar.navbar-fixed-bottom,
    .navbar.navbar-fixed-top {
      position: absolute;
      top: 50px;
      z-index: 0
    }

    .navbar.navbar-fixed-bottom .container,
    .navbar.navbar-fixed-top .container {
      max-width: 90%
    }

    .btn-group {
      margin-bottom: 10px
    }

    .form-inline input[type=password],
    .form-inline input[type=text],
    .form-inline select {
      width: 180px
    }

    .input-group {
      margin-bottom: 10px
    }

    .pagination {
      margin-top: 0
    }
  </style>

</head>

<body>
  <div class="container-fluid text-center" style="background-color: #414141; margin-bottom: 20px">
    <h2 style="color: #ffffff">Construction Management</h2>
    <a href="{% url 'mainfunction:dashboard' %}?user={{ user }}" class="btn btn-primary" style="float: left; color: #ffffff;">Back</a>
    <a href="{% url 'login:login' %}" class="btn btn-primary" style="float: right; color: #ffffff;">Logout</a>
  </div>

  <div class="row">
    <div class="col-sm-12 col-lg-12">
      <div class="row">
        <div class="container">
          <div style="color: red" id="err"></div>
          {% if error %}
            <div style="color: red"> {{ error }} </div>
          {% endif %}
          <form class="form-horizontal" action="{% url 'mainfunction:dashboard' %}?user={{ user }}" method="post">
            {% csrf_token %}
			{% for field in form %}
				<div class="form-group">
			      <label for="{{ field.id_for_lable }}" class="col-lg-2 control-label">{{ field.label_tag }}</label>
			      <div class="col-lg-10">
			        {{ field }}
			      </div>
			    </div>
			{% endfor %}
            <span class="form-group">
              <span class="col-lg-offset-2 col-lg-10">
                <button id="add" type="button" class="btn btn-default" onclick="loadDoc()">ADD</button>
              	<a class="btn btn-default" href="{% url 'mainfunction:dashboard' %}?user={{ user }}">BACK</a>
              </span>
            </span>
          </form>
        </div>
      </div>
    </div>
  </div>
  <footer class="text-center">
    <p>&copy; Construction Management</p>
    <div class="credits">
      <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version form: https://bootstrapmade.com/buy/?theme=Techie
      -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer>

  <!-- Main Scripts-->
  {% load static %}
  <script src="{% static 'login/jquery.js' %}"></script>
  {% load static %}
  <script src="{% static 'login/bootstrap.min.js' %}"></script>

  <!-- Bootstrap 3 has typeahead optionally -->
  {% load static %}
  <script src="{% static 'login/typeahead.min.js' %}"></script>   
</body>
</html>

mainfunction/templates/mainfunction/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta http-equiv="content-type" content="text/html; charset=UTF-8">

  <title>Login - Construction Management</title>

  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,400italic,700,900' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Techie Bootstrap 3 skin">
  <meta name="keywords" content="bootstrap 3, skin, flat">
  <meta name="author" content="bootstraptaste">

  <!-- Bootstrap css -->
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.min.css' %}" rel="stylesheet">
  {% load static %}
  <link type="text/css" href="{% static 'login/bootstrap.techie.css' %}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Techie
    Theme URL: https://bootstrapmade.com/techie-free-skin-bootstrap-3/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->

  <!-- Docs Custom styles -->
  <style>
    body,
    html {
      overflow-x: hidden
    }

    body {
      padding: 60px 20px 0
    }

    footer {
      border-top: 1px solid #ddd;
      padding: 30px;
      margin-top: 50px
    }

    .row>[class*=col-] {
      margin-bottom: 40px
    }

    .navbar-container {
      position: relative;
      min-height: 100px
    }

    .navbar.navbar-fixed-bottom,
    .navbar.navbar-fixed-top {
      position: absolute;
      top: 50px;
      z-index: 0
    }

    .navbar.navbar-fixed-bottom .container,
    .navbar.navbar-fixed-top .container {
      max-width: 90%
    }

    .btn-group {
      margin-bottom: 10px
    }

    .form-inline input[type=password],
    .form-inline input[type=text],
    .form-inline select {
      width: 180px
    }

    .input-group {
      margin-bottom: 10px
    }

    .pagination {
      margin-top: 0
    }
  </style>

</head>

<body>
  <div class="container-fluid text-center" style="background-color: #414141; margin-bottom: 20px">
    <h2 style="color: #ffffff">Construction Management</h2>
    <a href="{% url 'login:login' %}" class="btn btn-primary" style="float: right; color: #ffffff;">Logout</a>
  </div>
  <h3 style="color: #414141">Welcome {{ user }}</h3>
  <a href="{% url 'mainfunction:add_item'  %}?user={{ user }}" class="btn btn-primary" style="color: white; width: 10%; height: auto; margin-left: auto; margin-right: auto; display: block;"> Add Item </a>
  <br><br>
  <ul class="list-inline" style="list-style: none;">
      {% for project in project_details %}
        <li style="width: 33%; margin-bottom:10px;">
          <a href="{% url 'mainfunction:add_daily_details' project_name=project.0 %}?user={{ user }}" class="card" style="border: 2px solid #414141; text-align: center; background-color: #009688; color: white">
            <p>{{ project.0 }}</p>
            <p>{{ project.1 }}</p>
            <p>Day-{{ project.2 }}</p>
          </a>
        </li>
      {% endfor %}
  </ul>
</body>
</html>  